#ifndef SETTING_H
#define SETTING_H

#define BOARD_HEIGHT 32
#define BOARD_VISIBLE_HEIGHT 24
#define BOARD_SPAWN_HEIGHT 22

#define ENGINE_DEFAULT_STACK_HEIGHT 8
#define ENGINE_DEFAULT_EMPTY_LINE 9

#define ENGINE_STACK_FORCE_NEXT_LOOKUP 4



#endif //SETTING_H
